AWSTemplateFormatVersion: 2010-09-09

Parameters:
  LambdaBucketName:
    Type: "String"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref LambdaBucketName
