package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_kombustion//:kombustion.bzl", "kombustion_library")

# Export the kombustion config
kombustion_library(
    name = "kombustion",
    manifest = "kombustion.yaml",
)
